#pragma once
class FMODSound;
class AdvancedFollowInstance;
class SFXTriggerInstance;
class EventTriggerInstance;
class SongChannelState;
class SongTriggerState;
class SFXStateContainer;
class SFXTriggerState;
class ChanceObject;
class SmartPrefabResult;
class GameObjectPhysics;
class DynamicObjectAction;
class GJTransformState;
class CAState;
class GJPointDouble;
class SavedObjectStateRef;
class SavedActiveObjectState;
class SavedSpecialObjectState;
class SequenceTriggerState;
class FMODSoundTween;
class FMODQueuedMusic;
class SoundStateContainer;
class FMODSoundState;
class TimerItem;
class EnterEffectAnimValue;
class DynamicMoveCalculation;
class tk_spline;
class RecordCheckpoint;
class RecordButtonCommand;
class GJDropDownLayer;
class GJAccountDelegate;
class FLAlertLayerProtocol;
class AccountHelpLayer;
class GJAccountBackupDelegate;
class GJAccountSyncDelegate;
class AccountLayer;
class FLAlertLayer;
class TextInputDelegate;
class GJAccountLoginDelegate;
class AccountLoginLayer;
class GJAccountRegisterDelegate;
class AccountRegisterLayer;
class AchievementBar;
class CCIndexPath;
class TableViewCell;
class AchievementCell;
class AchievementManager;
class AchievementNotifier;
class AchievementsLayer;
class AdToolbox;
class CCSpritePlus;
class GameObject;
class EnhancedGameObject;
class EffectGameObject;
class AdvancedFollowTriggerObject;
class AdvancedFollowEditObject;
class AdvFollowSetup;
class AnimatedSpriteDelegate;
class SpritePartDelegate;
class AnimatedGameObject;
class CCAnimatedSprite;
class AnimatedShopKeeper;
class AppDelegate;
class ArtistCell;
class ArtTriggerGameObject;
class TableViewCellDelegate;
class MusicDownloadDelegate;
class AudioAssetsBrowser;
class AudioEffectsLayer;
class AudioLineGuideGameObject;
class BitmapFontCache;
class BonusDropdown;
class BoomListLayer;
class TableViewDelegate;
class TableViewDataSource;
class BoomListView;
class BoomScrollLayer;
class BoomScrollLayerDelegate;
class BrowseSmartTemplateLayer;
class BrowseSmartKeyLayer;
class ButtonPage;
class ButtonSprite;
class CameraTriggerGameObject;
class CCAlertCircle;
class CCAnimateFrameCache;
class CCBlockLayer;
class CCCircleWave;
class CCCircleAlert;
class CCCircleWaveDelegate;
class CCContentLayer;
class CCCountdown;
class CCCounterLabel;
class CCExtenderNode;
class CCLightFlash;
class CCLightStrip;
class CCMenuItemSpriteExtra;
class CCMenuItemToggler;
class CCMoveCNode;
class CCNodeContainer;
class CCPartAnimSprite;
class CCScrollLayerExt;
class CCScrollLayerExtDelegate;
class CCSpriteCOpacity;
class CCSpriteWithHue;
class CCSpriteGrayscale;
class CCSpritePart;
class CCTextInputNode;
class CCURLObject;
class GJChallengeDelegate;
class CurrencyRewardDelegate;
class ChallengesPage;
class GJChallengeItem;
class ChallengeNode;
class ChanceTriggerGameObject;
class CharacterColorDelegate;
class CharacterColorPage;
class CheckpointGameObject;
class EnterEffectInstance;
class GJValueTween;
class GJGameState;
class GJShaderState;
class FMODAudioState;
class PulseEffectAction;
class CountTriggerAction;
class OpacityEffectAction;
class TouchToggleAction;
class CollisionTriggerAction;
class ToggleTriggerAction;
class SpawnTriggerAction;
class KeyframeObject;
class GroupCommandObject2;
class TimerTriggerAction;
class EffectManagerState;
class CheckpointObject;
class CollisionBlockPopup;
class ColorAction;
class ColorAction2;
class ColorActionSprite;
class ColorChannelSprite;
class ColorSelectDelegate;
class ColorSelectLiveOverlay;
class ConfigureValuePopupDelegate;
class SliderDelegate;
class SetupTriggerPopup;
class GJSpecialColorSelectDelegate;
class ColorSelectPopup;
class ColorSetupDelegate;
class LikeItemDelegate;
class CommentCell;
class CommentUploadDelegate;
class CommunityCreditNode;
class CommunityCreditsPage;
class ConfigureHSVWidget;
class ConfigureValuePopup;
class CountTriggerGameObject;
class CreateGuidelinesLayer;
class CreateMenuItem;
class CreateParticlePopup;
class DialogDelegate;
class CreatorLayer;
class CurrencyRewardLayer;
class CurrencySprite;
class HSVWidgetDelegate;
class CustomizeObjectLayer;
class CustomizeObjectSettingsPopup;
class CustomListView;
class CustomSongDelegate;
class CustomSongCell;
class CustomMusicCell;
class CustomSFXDelegate;
class CustomSFXCell;
class CustomSFXWidget;
class GJDropDownLayerDelegate;
class MusicBrowserDelegate;
class CustomSongLayer;
class CustomSongLayerDelegate;
class GJAssetDownloadAction;
class CustomSongWidget;
class DailyLevelNode;
class GJDailyLevelDelegate;
class LevelDownloadDelegate;
class DailyLevelPage;
class RingObject;
class DashRingObject;
class DelayedSpawnNode;
class DemonFilterDelegate;
class DemonFilterSelectLayer;
class DemonInfoPopup;
class TextAreaDelegate;
class DialogLayer;
class DialogObject;
class DownloadMessageDelegate;
class DrawGridLayer;
class DungeonBarsSprite;
class DynamicBitset;
class DynamicScrollDelegate;
class EditButtonBar;
class EditGameObjectPopup;
class UploadActionDelegate;
class UploadPopupDelegate;
class SetIDPopupDelegate;
class EditLevelLayer;
class GJOptionsLayer;
class EditorOptionsLayer;
class EditorPauseLayer;
class GameObjectEditorState;
class GJRotationControlDelegate;
class GJScaleControlDelegate;
class GJTransformControlDelegate;
class EditorUI;
class EditTriggersPopup;
class EndLevelLayer;
class EndPortalObject;
class EndTriggerGameObject;
class EnhancedTriggerObject;
class EnterEffectObject;
class EventLinkTrigger;
class ExplodeItemNode;
class ExplodeItemSprite;
class ExtendedLayer;
class FileOperation;
class GManager;
class FileSaveManager;
class FindBPMLayer;
class SetIDPopup;
class FindObjectPopup;
class FMODMusic;
class FMODQueuedEffect;
class FMODAudioEngine;
class FMODLevelVisualizer;
class GameRateDelegate;
class RewardedVideoDelegate;
class FollowRewardPage;
class FontObject;
class ForceBlockGameObject;
class FriendRequestDelegate;
class FRequestProfilePage;
class FriendRequestPopup;
class UserListDelegate;
class FriendsProfilePage;
class GameCell;
class GameEffectsManager;
class GameLevelManager;
class GameLevelOptionsLayer;
class UIButtonConfig;
class GameManager;
class GameObjectCopy;
class GameOptionsLayer;
class GameOptionsTrigger;
class GameStatsManager;
class GameToolbox;
class LevelManagerDelegate;
class GauntletLayer;
class GauntletNode;
class GauntletSelectLayer;
class GauntletSprite;
class GhostTrailEffect;
class GJAccountManager;
class GJAccountSettingsDelegate;
class GJAccountSettingsLayer;
class GJActionManager;
class PlayerButtonCommand;
class TriggerEffectDelegate;
class GJBaseGameLayer;
class GJBigSprite;
class GJBigSpriteNode;
class GJChestSprite;
class GJColorSetupLayer;
class GJComment;
class GJCommentListLayer;
class GJDifficultySprite;
class GJEffectManager;
class GJGroundLayer;
class GJFlyGroundLayer;
class GJFollowCommandLayer;
class GJFriendRequest;
class GJGameLevel;
class GJGameLoadingLayer;
class ListButtonBarDelegate;
class GJGarageLayer;
class GJGradientLayer;
class GJHttpResult;
class GJItemIcon;
class GJLevelList;
class GJLevelScoreCell;
class GJListLayer;
class GJLocalLevelScoreCell;
class GJLocalScore;
class GJMapObject;
class GJMapPack;
class GJMessageCell;
class GJMessagePopup;
class GJMGLayer;
class GJMoreGamesLayer;
class GJMPDelegate;
class GJMultiplayerManager;
class GJObjectDecoder;
class GJOnlineRewardDelegate;
class GJPurchaseDelegate;
class GJPathPage;
class GJPathRewardPopup;
class GJPathsLayer;
class GJPathSprite;
class GJPFollowCommandLayer;
class GJPromoPopup;
class LevelRateInfoDelegate;
class GJRateLevelLayer;
class GJRequestCell;
class GJRewardDelegate;
class GJRewardItem;
class GJRewardObject;
class GJRobotSprite;
class GJRotateCommandLayer;
class GJRotationControl;
class GJScaleControl;
class GJScoreCell;
class GJSearchObject;
class GJShopLayer;
class GJSmartBlockPreview;
class GJSmartBlockPreviewSprite;
class GJSmartPrefab;
class GJSmartTemplate;
class GJSongBrowser;
class GJSpecialColorSelect;
class GJSpiderSprite;
class GJSpriteColor;
class GJStoreItem;
class GJTransformControl;
class GJUINode;
class GJUnlockableItem;
class GJUserCell;
class GJUserMessage;
class GJUserScore;
class GJWorldNode;
class UploadMessageDelegate;
class GJWriteMessagePopup;
class GooglePlayDelegate;
class GooglePlayManager;
class GradientTriggerObject;
class GraphicsReloadLayer;
class GravityEffectSprite;
class HardStreak;
class HSVLiveOverlay;
class HSVWidgetPopup;
class InfoAlertButton;
class LevelCommentDelegate;
class InfoLayer;
class InheritanceNode;
class ItemInfoPopup;
class ItemTriggerGameObject;
class KeybindingsLayer;
class KeybindingsManager;
class KeyframeAnimTriggerObject;
class KeyframeGameObject;
class LabelGameObject;
class LeaderboardManagerDelegate;
class LeaderboardsLayer;
class LevelAreaInnerLayer;
class LevelAreaLayer;
class SetTextPopupDelegate;
class ShareCommentDelegate;
class LevelBrowserLayer;
class LevelCell;
class LevelDeleteDelegate;
class LevelSettingsDelegate;
class LevelEditorLayer;
class LevelFeatureLayer;
class LevelUpdateDelegate;
class RateLevelDelegate;
class NumberInputDelegate;
class LevelInfoLayer;
class LevelLeaderboard;
class LevelListCell;
class LevelListDeleteDelegate;
class SelectListIconDelegate;
class LevelListLayer;
class LevelOptionsLayer;
class LevelOptionsLayer2;
class LevelPage;
class LevelSearchLayer;
class LevelSelectLayer;
class SelectArtDelegate;
class SelectSettingDelegate;
class LevelSettingsLayer;
class LevelSettingsObject;
class LevelTools;
class LevelUploadDelegate;
class LikeItemLayer;
class ListButtonBar;
class ListButtonPage;
class ListCell;
class ListUploadDelegate;
class LoadingCircle;
class LoadingCircleSprite;
class LoadingLayer;
class LocalLevelManager;
class MapPackCell;
class MapSelectLayer;
class MenuGameLayer;
class MenuLayer;
class MessageListDelegate;
class MessagesProfilePage;
class MoreOptionsLayer;
class MoreSearchLayer;
class MoreVideoOptionsLayer;
class MPLobbyLayer;
class MultilineBitmapFont;
class MultiplayerLayer;
class MultiTriggerPopup;
class MusicArtistObject;
class MusicBrowser;
class MusicDelegateHandler;
class PlatformDownloadDelegate;
class MusicDownloadManager;
class OptionsObjectDelegate;
class MusicSearchResult;
class NCSInfoLayer;
class NewgroundsInfoLayer;
class NodePoint;
class NumberInputLayer;
class OBB2D;
class ObjectControlGameObject;
class ObjectManager;
class ObjectToolbox;
class OnlineListDelegate;
class OptionsCell;
class OptionsLayer;
class OptionsObject;
class OptionsScrollLayer;
class ParentalOptionsLayer;
class ParticleGameObject;
class ParticlePreviewLayer;
class PauseLayer;
class PlatformToolbox;
class PlayerCheckpoint;
class PlayerControlGameObject;
class PlayerFireBoostSprite;
class PlayerObject;
class PlayLayer;
class PointNode;
class PriceLabel;
class UserInfoDelegate;
class ProfilePage;
class PromoInterstitial;
class PurchaseItemPopup;
class RandTriggerGameObject;
class RateDemonLayer;
class RateLevelLayer;
class RateStarsLayer;
class RetryLevelLayer;
class RewardsPage;
class RewardUnlockLayer;
class RotateGameplayGameObject;
class ScrollingLayer;
class SearchButton;
class SetTextPopup;
class SearchSFXPopup;
class SecretGame01Layer;
class SecretLayer;
class SecretLayer2;
class SecretLayer3;
class SecretLayer4;
class SecretLayer5;
class SecretLayer6;
class SecretNumberLayer;
class SecretRewardsLayer;
class SelectArtLayer;
class SelectEventLayer;
class SelectFontLayer;
class SelectListIconLayer;
class SelectPremadeDelegate;
class SelectPremadeLayer;
class SelectSettingLayer;
class SelectSFXSortDelegate;
class SelectSFXSortLayer;
class SequenceTriggerGameObject;
class SetColorIDPopup;
class SetFolderPopup;
class SetGroupIDLayer;
class SetItemIDLayer;
class SetLevelOrderPopup;
class SetTargetIDLayer;
class SetupAdvFollowEditPhysicsPopup;
class SetupAdvFollowPopup;
class SetupAdvFollowRetargetPopup;
class SetupAnimationPopup;
class SetupAnimSettingsPopup;
class SetupAreaMoveTriggerPopup;
class SetupAreaTintTriggerPopup;
class SetupAreaAnimTriggerPopup;
class SetupAreaFadeTriggerPopup;
class SetupAreaRotateTriggerPopup;
class SetupAreaTransformTriggerPopup;
class SetupAreaTriggerPopup;
class SetupArtSwitchPopup;
class SetupAudioLineGuidePopup;
class SetupAudioTriggerPopup;
class SetupBGSpeedTrigger;
class SetupCameraEdgePopup;
class SetupCameraGuidePopup;
class SetupCameraModePopup;
class SetupCameraOffsetTrigger;
class SetupCameraRotatePopup;
class SetupCameraRotatePopup2;
class SetupCheckpointPopup;
class SetupCoinLayer;
class SetupInstantCollisionTriggerPopup;
class SetupCollisionStateTriggerPopup;
class SetupCollisionTriggerPopup;
class SetupCountTriggerPopup;
class SetupDashRingPopup;
class SetupEndPopup;
class SetupEnterEffectPopup;
class SetupEnterTriggerPopup;
class SetupEventLinkPopup;
class SetupForceBlockPopup;
class SetupGameplayOffsetPopup;
class SetupGradientPopup;
class SetupGravityModPopup;
class SetupGravityTriggerPopup;
class SetupInstantCountPopup;
class SetupInteractObjectPopup;
class SetupItemCompareTriggerPopup;
class SetupItemEditTriggerPopup;
class SetupKeyframeAnimPopup;
class SetupKeyframePopup;
class SetupMGTrigger;
class SetupMoveCommandPopup;
class SetupObjectControlPopup;
class SetupObjectOptions2Popup;
class SetupObjectOptionsPopup;
class SetupObjectTogglePopup;
class SetupOpacityPopup;
class SetupOptionsTriggerPopup;
class SetupPersistentItemTriggerPopup;
class SetupPickupTriggerPopup;
class SetupPlatformerEndPopup;
class SetupPlayerControlPopup;
class SetupPortalPopup;
class SetupPulsePopup;
class SetupRandAdvTriggerPopup;
class SetupRandTriggerPopup;
class SetupResetTriggerPopup;
class SetupReverbPopup;
class SetupRotateCommandPopup;
class SetupRotateGameplayPopup;
class SetupRotatePopup;
class SetupSequenceTriggerPopup;
class SetupSFXEditPopup;
class SFXBrowserDelegate;
class SetupSFXPopup;
class SetupShaderEffectPopup;
class SetupShakePopup;
class SetupSmartBlockLayer;
class SetupSmartTemplateLayer;
class SongPlaybackDelegate;
class SetupSongTriggerPopup;
class SetupSpawnParticlePopup;
class SetupSpawnPopup;
class SetupStaticCameraPopup;
class SetupStopTriggerPopup;
class SetupTeleportPopup;
class SetupTimerControlTriggerPopup;
class SetupTimerEventTriggerPopup;
class SetupTimerTriggerPopup;
class SetupTimeWarpPopup;
class SetupTouchTogglePopup;
class SetupTransformPopup;
class SetupZoomTriggerPopup;
class SFXBrowser;
class SFXInfoObject;
class SFXFolderObject;
class SFXSearchResult;
class SFXTriggerGameObject;
class ShaderGameObject;
class ShaderLayer;
class ShardsPage;
class ShareCommentLayer;
class ShareLevelLayer;
class ShareLevelSettingsLayer;
class ShareListLayer;
class SimpleObject;
class SimplePlayer;
class SlideInLayer;
class SliderThumb;
class SliderTouchLogic;
class Slider;
class SmartGameObject;
class SmartTemplateCell;
class SongCell;
class SongInfoLayer;
class SongInfoObject;
class SongObject;
class SongOptionsLayer;
class SongSelectNode;
class SongsLayer;
class SongTriggerGameObject;
class SpawnParticleGameObject;
class SpawnTriggerGameObject;
class SpecialAnimGameObject;
class SpriteAnimationManager;
class SpriteDescription;
class StarInfoPopup;
class StartPosObject;
class StatsCell;
class StatsLayer;
class StatsObject;
class SupportLayer;
class TableView;
class TeleportPortalObject;
class TextAlertPopup;
class TextArea;
class TextGameObject;
class TextStyleSection;
class TimerTriggerGameObject;
class TopArtistsLayer;
class TOSPopup;
class TransformTriggerGameObject;
class TriggerControlGameObject;
class TutorialLayer;
class TutorialPopup;
class UILayer;
class UIObjectSettingsPopup;
class UIOptionsLayer;
class UIPOptionsLayer;
class UISaveLoadLayer;
class UISettingsGameObject;
class UndoObject;
class UpdateAccountSettingsPopup;
class UploadActionPopup;
class UploadListPopup;
class UploadPopup;
class URLCell;
class URLViewLayer;
class VideoOptionsLayer;
class WorldLevelPage;
class WorldSelectLayer;

struct TodoReturnPlaceholder {
private:
    TodoReturnPlaceholder() = default;
    TodoReturnPlaceholder(TodoReturnPlaceholder const&) = default;
    TodoReturnPlaceholder(TodoReturnPlaceholder&&) = default;
    ~TodoReturnPlaceholder() = default;
public:
    friend class FMODSound;
    friend class AdvancedFollowInstance;
    friend class SFXTriggerInstance;
    friend class EventTriggerInstance;
    friend class SongChannelState;
    friend class SongTriggerState;
    friend class SFXStateContainer;
    friend class SFXTriggerState;
    friend class ChanceObject;
    friend class SmartPrefabResult;
    friend class GameObjectPhysics;
    friend class DynamicObjectAction;
    friend class GJTransformState;
    friend class CAState;
    friend class GJPointDouble;
    friend class SavedObjectStateRef;
    friend class SavedActiveObjectState;
    friend class SavedSpecialObjectState;
    friend class SequenceTriggerState;
    friend class FMODSoundTween;
    friend class FMODQueuedMusic;
    friend class SoundStateContainer;
    friend class FMODSoundState;
    friend class TimerItem;
    friend class EnterEffectAnimValue;
    friend class DynamicMoveCalculation;
    friend class tk_spline;
    friend class RecordCheckpoint;
    friend class RecordButtonCommand;
    friend class GJDropDownLayer;
    friend class GJAccountDelegate;
    friend class FLAlertLayerProtocol;
    friend class AccountHelpLayer;
    friend class GJAccountBackupDelegate;
    friend class GJAccountSyncDelegate;
    friend class AccountLayer;
    friend class FLAlertLayer;
    friend class TextInputDelegate;
    friend class GJAccountLoginDelegate;
    friend class AccountLoginLayer;
    friend class GJAccountRegisterDelegate;
    friend class AccountRegisterLayer;
    friend class AchievementBar;
    friend class CCIndexPath;
    friend class TableViewCell;
    friend class AchievementCell;
    friend class AchievementManager;
    friend class AchievementNotifier;
    friend class AchievementsLayer;
    friend class AdToolbox;
    friend class CCSpritePlus;
    friend class GameObject;
    friend class EnhancedGameObject;
    friend class EffectGameObject;
    friend class AdvancedFollowTriggerObject;
    friend class AdvancedFollowEditObject;
    friend class AdvFollowSetup;
    friend class AnimatedSpriteDelegate;
    friend class SpritePartDelegate;
    friend class AnimatedGameObject;
    friend class CCAnimatedSprite;
    friend class AnimatedShopKeeper;
    friend class AppDelegate;
    friend class ArtistCell;
    friend class ArtTriggerGameObject;
    friend class TableViewCellDelegate;
    friend class MusicDownloadDelegate;
    friend class AudioAssetsBrowser;
    friend class AudioEffectsLayer;
    friend class AudioLineGuideGameObject;
    friend class BitmapFontCache;
    friend class BonusDropdown;
    friend class BoomListLayer;
    friend class TableViewDelegate;
    friend class TableViewDataSource;
    friend class BoomListView;
    friend class BoomScrollLayer;
    friend class BoomScrollLayerDelegate;
    friend class BrowseSmartTemplateLayer;
    friend class BrowseSmartKeyLayer;
    friend class ButtonPage;
    friend class ButtonSprite;
    friend class CameraTriggerGameObject;
    friend class CCAlertCircle;
    friend class CCAnimateFrameCache;
    friend class CCBlockLayer;
    friend class CCCircleWave;
    friend class CCCircleAlert;
    friend class CCCircleWaveDelegate;
    friend class CCContentLayer;
    friend class CCCountdown;
    friend class CCCounterLabel;
    friend class CCExtenderNode;
    friend class CCLightFlash;
    friend class CCLightStrip;
    friend class CCMenuItemSpriteExtra;
    friend class CCMenuItemToggler;
    friend class CCMoveCNode;
    friend class CCNodeContainer;
    friend class CCPartAnimSprite;
    friend class CCScrollLayerExt;
    friend class CCScrollLayerExtDelegate;
    friend class CCSpriteCOpacity;
    friend class CCSpriteWithHue;
    friend class CCSpriteGrayscale;
    friend class CCSpritePart;
    friend class CCTextInputNode;
    friend class CCURLObject;
    friend class GJChallengeDelegate;
    friend class CurrencyRewardDelegate;
    friend class ChallengesPage;
    friend class GJChallengeItem;
    friend class ChallengeNode;
    friend class ChanceTriggerGameObject;
    friend class CharacterColorDelegate;
    friend class CharacterColorPage;
    friend class CheckpointGameObject;
    friend class EnterEffectInstance;
    friend class GJValueTween;
    friend class GJGameState;
    friend class GJShaderState;
    friend class FMODAudioState;
    friend class PulseEffectAction;
    friend class CountTriggerAction;
    friend class OpacityEffectAction;
    friend class TouchToggleAction;
    friend class CollisionTriggerAction;
    friend class ToggleTriggerAction;
    friend class SpawnTriggerAction;
    friend class KeyframeObject;
    friend class GroupCommandObject2;
    friend class TimerTriggerAction;
    friend class EffectManagerState;
    friend class CheckpointObject;
    friend class CollisionBlockPopup;
    friend class ColorAction;
    friend class ColorAction2;
    friend class ColorActionSprite;
    friend class ColorChannelSprite;
    friend class ColorSelectDelegate;
    friend class ColorSelectLiveOverlay;
    friend class ConfigureValuePopupDelegate;
    friend class SliderDelegate;
    friend class SetupTriggerPopup;
    friend class GJSpecialColorSelectDelegate;
    friend class ColorSelectPopup;
    friend class ColorSetupDelegate;
    friend class LikeItemDelegate;
    friend class CommentCell;
    friend class CommentUploadDelegate;
    friend class CommunityCreditNode;
    friend class CommunityCreditsPage;
    friend class ConfigureHSVWidget;
    friend class ConfigureValuePopup;
    friend class CountTriggerGameObject;
    friend class CreateGuidelinesLayer;
    friend class CreateMenuItem;
    friend class CreateParticlePopup;
    friend class DialogDelegate;
    friend class CreatorLayer;
    friend class CurrencyRewardLayer;
    friend class CurrencySprite;
    friend class HSVWidgetDelegate;
    friend class CustomizeObjectLayer;
    friend class CustomizeObjectSettingsPopup;
    friend class CustomListView;
    friend class CustomSongDelegate;
    friend class CustomSongCell;
    friend class CustomMusicCell;
    friend class CustomSFXDelegate;
    friend class CustomSFXCell;
    friend class CustomSFXWidget;
    friend class GJDropDownLayerDelegate;
    friend class MusicBrowserDelegate;
    friend class CustomSongLayer;
    friend class CustomSongLayerDelegate;
    friend class GJAssetDownloadAction;
    friend class CustomSongWidget;
    friend class DailyLevelNode;
    friend class GJDailyLevelDelegate;
    friend class LevelDownloadDelegate;
    friend class DailyLevelPage;
    friend class RingObject;
    friend class DashRingObject;
    friend class DelayedSpawnNode;
    friend class DemonFilterDelegate;
    friend class DemonFilterSelectLayer;
    friend class DemonInfoPopup;
    friend class TextAreaDelegate;
    friend class DialogLayer;
    friend class DialogObject;
    friend class DownloadMessageDelegate;
    friend class DrawGridLayer;
    friend class DungeonBarsSprite;
    friend class DynamicBitset;
    friend class DynamicScrollDelegate;
    friend class EditButtonBar;
    friend class EditGameObjectPopup;
    friend class UploadActionDelegate;
    friend class UploadPopupDelegate;
    friend class SetIDPopupDelegate;
    friend class EditLevelLayer;
    friend class GJOptionsLayer;
    friend class EditorOptionsLayer;
    friend class EditorPauseLayer;
    friend class GameObjectEditorState;
    friend class GJRotationControlDelegate;
    friend class GJScaleControlDelegate;
    friend class GJTransformControlDelegate;
    friend class EditorUI;
    friend class EditTriggersPopup;
    friend class EndLevelLayer;
    friend class EndPortalObject;
    friend class EndTriggerGameObject;
    friend class EnhancedTriggerObject;
    friend class EnterEffectObject;
    friend class EventLinkTrigger;
    friend class ExplodeItemNode;
    friend class ExplodeItemSprite;
    friend class ExtendedLayer;
    friend class FileOperation;
    friend class GManager;
    friend class FileSaveManager;
    friend class FindBPMLayer;
    friend class SetIDPopup;
    friend class FindObjectPopup;
    friend class FMODMusic;
    friend class FMODQueuedEffect;
    friend class FMODAudioEngine;
    friend class FMODLevelVisualizer;
    friend class GameRateDelegate;
    friend class RewardedVideoDelegate;
    friend class FollowRewardPage;
    friend class FontObject;
    friend class ForceBlockGameObject;
    friend class FriendRequestDelegate;
    friend class FRequestProfilePage;
    friend class FriendRequestPopup;
    friend class UserListDelegate;
    friend class FriendsProfilePage;
    friend class GameCell;
    friend class GameEffectsManager;
    friend class GameLevelManager;
    friend class GameLevelOptionsLayer;
    friend class UIButtonConfig;
    friend class GameManager;
    friend class GameObjectCopy;
    friend class GameOptionsLayer;
    friend class GameOptionsTrigger;
    friend class GameStatsManager;
    friend class GameToolbox;
    friend class LevelManagerDelegate;
    friend class GauntletLayer;
    friend class GauntletNode;
    friend class GauntletSelectLayer;
    friend class GauntletSprite;
    friend class GhostTrailEffect;
    friend class GJAccountManager;
    friend class GJAccountSettingsDelegate;
    friend class GJAccountSettingsLayer;
    friend class GJActionManager;
    friend class PlayerButtonCommand;
    friend class TriggerEffectDelegate;
    friend class GJBaseGameLayer;
    friend class GJBigSprite;
    friend class GJBigSpriteNode;
    friend class GJChestSprite;
    friend class GJColorSetupLayer;
    friend class GJComment;
    friend class GJCommentListLayer;
    friend class GJDifficultySprite;
    friend class GJEffectManager;
    friend class GJGroundLayer;
    friend class GJFlyGroundLayer;
    friend class GJFollowCommandLayer;
    friend class GJFriendRequest;
    friend class GJGameLevel;
    friend class GJGameLoadingLayer;
    friend class ListButtonBarDelegate;
    friend class GJGarageLayer;
    friend class GJGradientLayer;
    friend class GJHttpResult;
    friend class GJItemIcon;
    friend class GJLevelList;
    friend class GJLevelScoreCell;
    friend class GJListLayer;
    friend class GJLocalLevelScoreCell;
    friend class GJLocalScore;
    friend class GJMapObject;
    friend class GJMapPack;
    friend class GJMessageCell;
    friend class GJMessagePopup;
    friend class GJMGLayer;
    friend class GJMoreGamesLayer;
    friend class GJMPDelegate;
    friend class GJMultiplayerManager;
    friend class GJObjectDecoder;
    friend class GJOnlineRewardDelegate;
    friend class GJPurchaseDelegate;
    friend class GJPathPage;
    friend class GJPathRewardPopup;
    friend class GJPathsLayer;
    friend class GJPathSprite;
    friend class GJPFollowCommandLayer;
    friend class GJPromoPopup;
    friend class LevelRateInfoDelegate;
    friend class GJRateLevelLayer;
    friend class GJRequestCell;
    friend class GJRewardDelegate;
    friend class GJRewardItem;
    friend class GJRewardObject;
    friend class GJRobotSprite;
    friend class GJRotateCommandLayer;
    friend class GJRotationControl;
    friend class GJScaleControl;
    friend class GJScoreCell;
    friend class GJSearchObject;
    friend class GJShopLayer;
    friend class GJSmartBlockPreview;
    friend class GJSmartBlockPreviewSprite;
    friend class GJSmartPrefab;
    friend class GJSmartTemplate;
    friend class GJSongBrowser;
    friend class GJSpecialColorSelect;
    friend class GJSpiderSprite;
    friend class GJSpriteColor;
    friend class GJStoreItem;
    friend class GJTransformControl;
    friend class GJUINode;
    friend class GJUnlockableItem;
    friend class GJUserCell;
    friend class GJUserMessage;
    friend class GJUserScore;
    friend class GJWorldNode;
    friend class UploadMessageDelegate;
    friend class GJWriteMessagePopup;
    friend class GooglePlayDelegate;
    friend class GooglePlayManager;
    friend class GradientTriggerObject;
    friend class GraphicsReloadLayer;
    friend class GravityEffectSprite;
    friend class HardStreak;
    friend class HSVLiveOverlay;
    friend class HSVWidgetPopup;
    friend class InfoAlertButton;
    friend class LevelCommentDelegate;
    friend class InfoLayer;
    friend class InheritanceNode;
    friend class ItemInfoPopup;
    friend class ItemTriggerGameObject;
    friend class KeybindingsLayer;
    friend class KeybindingsManager;
    friend class KeyframeAnimTriggerObject;
    friend class KeyframeGameObject;
    friend class LabelGameObject;
    friend class LeaderboardManagerDelegate;
    friend class LeaderboardsLayer;
    friend class LevelAreaInnerLayer;
    friend class LevelAreaLayer;
    friend class SetTextPopupDelegate;
    friend class ShareCommentDelegate;
    friend class LevelBrowserLayer;
    friend class LevelCell;
    friend class LevelDeleteDelegate;
    friend class LevelSettingsDelegate;
    friend class LevelEditorLayer;
    friend class LevelFeatureLayer;
    friend class LevelUpdateDelegate;
    friend class RateLevelDelegate;
    friend class NumberInputDelegate;
    friend class LevelInfoLayer;
    friend class LevelLeaderboard;
    friend class LevelListCell;
    friend class LevelListDeleteDelegate;
    friend class SelectListIconDelegate;
    friend class LevelListLayer;
    friend class LevelOptionsLayer;
    friend class LevelOptionsLayer2;
    friend class LevelPage;
    friend class LevelSearchLayer;
    friend class LevelSelectLayer;
    friend class SelectArtDelegate;
    friend class SelectSettingDelegate;
    friend class LevelSettingsLayer;
    friend class LevelSettingsObject;
    friend class LevelTools;
    friend class LevelUploadDelegate;
    friend class LikeItemLayer;
    friend class ListButtonBar;
    friend class ListButtonPage;
    friend class ListCell;
    friend class ListUploadDelegate;
    friend class LoadingCircle;
    friend class LoadingCircleSprite;
    friend class LoadingLayer;
    friend class LocalLevelManager;
    friend class MapPackCell;
    friend class MapSelectLayer;
    friend class MenuGameLayer;
    friend class MenuLayer;
    friend class MessageListDelegate;
    friend class MessagesProfilePage;
    friend class MoreOptionsLayer;
    friend class MoreSearchLayer;
    friend class MoreVideoOptionsLayer;
    friend class MPLobbyLayer;
    friend class MultilineBitmapFont;
    friend class MultiplayerLayer;
    friend class MultiTriggerPopup;
    friend class MusicArtistObject;
    friend class MusicBrowser;
    friend class MusicDelegateHandler;
    friend class PlatformDownloadDelegate;
    friend class MusicDownloadManager;
    friend class OptionsObjectDelegate;
    friend class MusicSearchResult;
    friend class NCSInfoLayer;
    friend class NewgroundsInfoLayer;
    friend class NodePoint;
    friend class NumberInputLayer;
    friend class OBB2D;
    friend class ObjectControlGameObject;
    friend class ObjectManager;
    friend class ObjectToolbox;
    friend class OnlineListDelegate;
    friend class OptionsCell;
    friend class OptionsLayer;
    friend class OptionsObject;
    friend class OptionsScrollLayer;
    friend class ParentalOptionsLayer;
    friend class ParticleGameObject;
    friend class ParticlePreviewLayer;
    friend class PauseLayer;
    friend class PlatformToolbox;
    friend class PlayerCheckpoint;
    friend class PlayerControlGameObject;
    friend class PlayerFireBoostSprite;
    friend class PlayerObject;
    friend class PlayLayer;
    friend class PointNode;
    friend class PriceLabel;
    friend class UserInfoDelegate;
    friend class ProfilePage;
    friend class PromoInterstitial;
    friend class PurchaseItemPopup;
    friend class RandTriggerGameObject;
    friend class RateDemonLayer;
    friend class RateLevelLayer;
    friend class RateStarsLayer;
    friend class RetryLevelLayer;
    friend class RewardsPage;
    friend class RewardUnlockLayer;
    friend class RotateGameplayGameObject;
    friend class ScrollingLayer;
    friend class SearchButton;
    friend class SetTextPopup;
    friend class SearchSFXPopup;
    friend class SecretGame01Layer;
    friend class SecretLayer;
    friend class SecretLayer2;
    friend class SecretLayer3;
    friend class SecretLayer4;
    friend class SecretLayer5;
    friend class SecretLayer6;
    friend class SecretNumberLayer;
    friend class SecretRewardsLayer;
    friend class SelectArtLayer;
    friend class SelectEventLayer;
    friend class SelectFontLayer;
    friend class SelectListIconLayer;
    friend class SelectPremadeDelegate;
    friend class SelectPremadeLayer;
    friend class SelectSettingLayer;
    friend class SelectSFXSortDelegate;
    friend class SelectSFXSortLayer;
    friend class SequenceTriggerGameObject;
    friend class SetColorIDPopup;
    friend class SetFolderPopup;
    friend class SetGroupIDLayer;
    friend class SetItemIDLayer;
    friend class SetLevelOrderPopup;
    friend class SetTargetIDLayer;
    friend class SetupAdvFollowEditPhysicsPopup;
    friend class SetupAdvFollowPopup;
    friend class SetupAdvFollowRetargetPopup;
    friend class SetupAnimationPopup;
    friend class SetupAnimSettingsPopup;
    friend class SetupAreaMoveTriggerPopup;
    friend class SetupAreaTintTriggerPopup;
    friend class SetupAreaAnimTriggerPopup;
    friend class SetupAreaFadeTriggerPopup;
    friend class SetupAreaRotateTriggerPopup;
    friend class SetupAreaTransformTriggerPopup;
    friend class SetupAreaTriggerPopup;
    friend class SetupArtSwitchPopup;
    friend class SetupAudioLineGuidePopup;
    friend class SetupAudioTriggerPopup;
    friend class SetupBGSpeedTrigger;
    friend class SetupCameraEdgePopup;
    friend class SetupCameraGuidePopup;
    friend class SetupCameraModePopup;
    friend class SetupCameraOffsetTrigger;
    friend class SetupCameraRotatePopup;
    friend class SetupCameraRotatePopup2;
    friend class SetupCheckpointPopup;
    friend class SetupCoinLayer;
    friend class SetupInstantCollisionTriggerPopup;
    friend class SetupCollisionStateTriggerPopup;
    friend class SetupCollisionTriggerPopup;
    friend class SetupCountTriggerPopup;
    friend class SetupDashRingPopup;
    friend class SetupEndPopup;
    friend class SetupEnterEffectPopup;
    friend class SetupEnterTriggerPopup;
    friend class SetupEventLinkPopup;
    friend class SetupForceBlockPopup;
    friend class SetupGameplayOffsetPopup;
    friend class SetupGradientPopup;
    friend class SetupGravityModPopup;
    friend class SetupGravityTriggerPopup;
    friend class SetupInstantCountPopup;
    friend class SetupInteractObjectPopup;
    friend class SetupItemCompareTriggerPopup;
    friend class SetupItemEditTriggerPopup;
    friend class SetupKeyframeAnimPopup;
    friend class SetupKeyframePopup;
    friend class SetupMGTrigger;
    friend class SetupMoveCommandPopup;
    friend class SetupObjectControlPopup;
    friend class SetupObjectOptions2Popup;
    friend class SetupObjectOptionsPopup;
    friend class SetupObjectTogglePopup;
    friend class SetupOpacityPopup;
    friend class SetupOptionsTriggerPopup;
    friend class SetupPersistentItemTriggerPopup;
    friend class SetupPickupTriggerPopup;
    friend class SetupPlatformerEndPopup;
    friend class SetupPlayerControlPopup;
    friend class SetupPortalPopup;
    friend class SetupPulsePopup;
    friend class SetupRandAdvTriggerPopup;
    friend class SetupRandTriggerPopup;
    friend class SetupResetTriggerPopup;
    friend class SetupReverbPopup;
    friend class SetupRotateCommandPopup;
    friend class SetupRotateGameplayPopup;
    friend class SetupRotatePopup;
    friend class SetupSequenceTriggerPopup;
    friend class SetupSFXEditPopup;
    friend class SFXBrowserDelegate;
    friend class SetupSFXPopup;
    friend class SetupShaderEffectPopup;
    friend class SetupShakePopup;
    friend class SetupSmartBlockLayer;
    friend class SetupSmartTemplateLayer;
    friend class SongPlaybackDelegate;
    friend class SetupSongTriggerPopup;
    friend class SetupSpawnParticlePopup;
    friend class SetupSpawnPopup;
    friend class SetupStaticCameraPopup;
    friend class SetupStopTriggerPopup;
    friend class SetupTeleportPopup;
    friend class SetupTimerControlTriggerPopup;
    friend class SetupTimerEventTriggerPopup;
    friend class SetupTimerTriggerPopup;
    friend class SetupTimeWarpPopup;
    friend class SetupTouchTogglePopup;
    friend class SetupTransformPopup;
    friend class SetupZoomTriggerPopup;
    friend class SFXBrowser;
    friend class SFXInfoObject;
    friend class SFXFolderObject;
    friend class SFXSearchResult;
    friend class SFXTriggerGameObject;
    friend class ShaderGameObject;
    friend class ShaderLayer;
    friend class ShardsPage;
    friend class ShareCommentLayer;
    friend class ShareLevelLayer;
    friend class ShareLevelSettingsLayer;
    friend class ShareListLayer;
    friend class SimpleObject;
    friend class SimplePlayer;
    friend class SlideInLayer;
    friend class SliderThumb;
    friend class SliderTouchLogic;
    friend class Slider;
    friend class SmartGameObject;
    friend class SmartTemplateCell;
    friend class SongCell;
    friend class SongInfoLayer;
    friend class SongInfoObject;
    friend class SongObject;
    friend class SongOptionsLayer;
    friend class SongSelectNode;
    friend class SongsLayer;
    friend class SongTriggerGameObject;
    friend class SpawnParticleGameObject;
    friend class SpawnTriggerGameObject;
    friend class SpecialAnimGameObject;
    friend class SpriteAnimationManager;
    friend class SpriteDescription;
    friend class StarInfoPopup;
    friend class StartPosObject;
    friend class StatsCell;
    friend class StatsLayer;
    friend class StatsObject;
    friend class SupportLayer;
    friend class TableView;
    friend class TeleportPortalObject;
    friend class TextAlertPopup;
    friend class TextArea;
    friend class TextGameObject;
    friend class TextStyleSection;
    friend class TimerTriggerGameObject;
    friend class TopArtistsLayer;
    friend class TOSPopup;
    friend class TransformTriggerGameObject;
    friend class TriggerControlGameObject;
    friend class TutorialLayer;
    friend class TutorialPopup;
    friend class UILayer;
    friend class UIObjectSettingsPopup;
    friend class UIOptionsLayer;
    friend class UIPOptionsLayer;
    friend class UISaveLoadLayer;
    friend class UISettingsGameObject;
    friend class UndoObject;
    friend class UpdateAccountSettingsPopup;
    friend class UploadActionPopup;
    friend class UploadListPopup;
    friend class UploadPopup;
    friend class URLCell;
    friend class URLViewLayer;
    friend class VideoOptionsLayer;
    friend class WorldLevelPage;
    friend class WorldSelectLayer;

};
